/**
 * Golden tests for the conjugation engine + formatters.
 *
 * Builds an in-memory DB from tests/fixtures/entries/*.json using the REAL
 * transform/buildDb code (conjugations generated by src/conjugation.ts), then
 * runs conjugate/deconjugate output against the golden files in
 * tests/fixtures/golden/ (byte-for-byte).
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import Database from "better-sqlite3";
import { transform, type Transformed } from "../data/build/transform.js";

type DB = InstanceType<typeof Database>;
import { buildDb } from "../data/build/buildDb.js";
import { renderConjugate, renderDeconjugate, FORM_LABELS, type ConjRow, type WordLike } from "../src/format.js";
import type { JmdictWord } from "../data/build/parse.js";

const FIXTURES = "tests/fixtures";

function loadJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

function fixtureDir(dir: string): string[] {
  return readdirSync(join(FIXTURES, dir)).filter((f) => f.endsWith(".json"));
}

/** Build the fixture DB using the real pipeline code (conjugations included). */
function buildFixtureDb(): DB {
  const words: JmdictWord[] = fixtureDir("entries")
    .filter((f) => f.startsWith("jmdict-"))
    .map((f) => loadJson<JmdictWord>(join(FIXTURES, "entries", f)));

  const jmdict = { words } as never; // transform only reads .words
  const kanjidic2 = { characters: [] } as never;
  const kradfile = { kanji: {} } as never;
  const radkfile = { radicals: {} } as never;

  const rows = transform(jmdict, kanjidic2, kradfile, radkfile) as Transformed;
  const tags = loadJson<Record<string, string>>(join(FIXTURES, "meta", "tags.json"));
  const db = buildDb(rows, { tags: JSON.stringify(tags) }, { dbPath: ":memory:" });
  return db;
}

function loadWord(db: DB, id: string): WordLike {
  const kanji = db.prepare("SELECT text, common FROM writings WHERE word_id = ? AND kind = 'kanji' ORDER BY id").all(id) as { text: string; common: number }[];
  const kana = db.prepare("SELECT text, common FROM writings WHERE word_id = ? AND kind = 'kana' ORDER BY id").all(id) as { text: string; common: number }[];
  const senses = db.prepare("SELECT part_of_speech FROM senses WHERE word_id = ? ORDER BY position").all(id) as { part_of_speech: string }[];
  return {
    id,
    kanji: kanji.map((k) => ({ text: k.text, common: k.common === 1 })),
    kana: kana.map((k) => ({ text: k.text, common: k.common === 1 })),
    sense: senses.map((s) => ({ partOfSpeech: JSON.parse(s.part_of_speech) as string[] })),
  };
}

function conjugate(db: DB, wordId: string): string {
  const word = loadWord(db, wordId);
  const rows = db.prepare("SELECT class, form, value, display FROM conjugations WHERE word_id = ?").all(wordId) as ConjRow[];
  return renderConjugate(word, rows);
}

function deconjugate(db: DB, form: string, tags: Record<string, string>): string {
  const rows = db.prepare(
    "SELECT word_id, form, display FROM conjugations WHERE display = ? OR value = ? ORDER BY word_id",
  ).all(form, form) as { word_id: string; form: string; display: string | null }[];
  const matches = rows.map((r) => ({
    word: loadWord(db, r.word_id),
    formLabel: FORM_LABELS[r.form] ?? r.form,
  }));
  return renderDeconjugate(form, matches, tags);
}

function golden(name: string): string {
  return readFileSync(join(FIXTURES, "golden", name), "utf-8");
}

const CONJUGATE_GOLDENS: [string, string][] = [
  ["conjugate-taberu.txt", "1358280"],
  ["conjugate-kuru.txt", "1547720"],
  ["conjugate-suru.txt", "1157170"],
  ["conjugate-yoi.txt", "1605820"],
  ["conjugate-ii.txt", "2820690"],
  ["conjugate-aru.txt", "1296400"],
  ["conjugate-shokuji.txt", "1358490"],
  ["conjugate-kanzuru.txt", "1609650"],
  // per-class [G] gap fixtures: vs-c 死す, vs-s 愛する, v5uru 覆う (synthetic), vs-a 検討 (synthetic)
  ["conjugate-shisu.txt", "2410560"],
  ["conjugate-aisuru.txt", "1150450"],
  ["conjugate-ou.txt", "9000101"],
  ["conjugate-kentou.txt", "9000102"],
];

const DECONJUGATE_GOLDENS: [string, string][] = [
  ["deconjugate-tabete.txt", "食べて"],
  ["deconjugate-nai.txt", "ない"],
  ["deconjugate-shokujishite.txt", "食事して"],
  ["deconjugate-nomatch.txt", "わからないもの"],
];

const tags = loadJson<Record<string, string>>(join(FIXTURES, "meta", "tags.json"));

test("conjugate goldens (engine output byte-for-byte)", () => {
  const db = buildFixtureDb();
  try {
    for (const [file, wordId] of CONJUGATE_GOLDENS) {
      assert.equal(conjugate(db, wordId), golden(file), file);
    }
  } finally {
    db.close();
  }
});

test("deconjugate goldens", () => {
  const db = buildFixtureDb();
  try {
    for (const [file, form] of DECONJUGATE_GOLDENS) {
      assert.equal(deconjugate(db, form, tags), golden(file), file);
    }
  } finally {
    db.close();
  }
});

test("conjugations table populated for all conjugatable fixture words", () => {
  const db = buildFixtureDb();
  try {
    const count = db.prepare("SELECT COUNT(*) AS n FROM conjugations").get() as { n: number };
    const wordCount = db.prepare("SELECT COUNT(DISTINCT word_id) AS n FROM conjugations").get() as { n: number };
    // fixture words with conjugatable POS: taberu, kuru, suru, yoi, ii, aru,
    // shokuji, kanzuru, nomu, kuu, atsui, kirei, samui, iru, plus the
    // per-class gap words shisu (vs-c), aisuru (vs-s), ou (v5uru), kentou (vs-a)
    assert.equal(wordCount.n, 18);
    assert.ok(count.n > 12 * 8, `expected >96 rows, got ${count.n}`);
  } finally {
    db.close();
  }
});

test("deconjugate round-trip: every display value finds its word", () => {
  const db = buildFixtureDb();
  try {
    const rows = db.prepare("SELECT DISTINCT display FROM conjugations WHERE display IS NOT NULL").all() as { display: string }[];
    for (const { display } of rows) {
      const found = db.prepare("SELECT COUNT(*) AS n FROM conjugations WHERE display = ? OR value = ?").get(display, display) as { n: number };
      assert.ok(found.n >= 1, `no match for ${display}`);
    }
  } finally {
    db.close();
  }
});
