/**
 * Version stamp tests.
 *
 * src/version.ts is GENERATED by scripts/version.mjs (bumped by every build
 * and every commit), and is the single source of truth shared by the CLI
 * (`omakase --version`) and the web app (header badge). These
 * tests pin the shape of the stamp and that the generator's read-only mode
 * agrees with the committed module.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { APP_VERSION, BUILD, COMMITS, COMMIT, COMMIT_DATE, VERSION, VERSION_FULL } from "../src/version.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

test("app version matches package.json", () => {
  const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { version: string };
  assert.equal(APP_VERSION, pkg.version);
});

test("version fields are well-formed and consistent", () => {
  assert.ok(Number.isInteger(BUILD) && BUILD >= 0, `BUILD=${BUILD}`);
  assert.ok(Number.isInteger(COMMITS) && COMMITS >= 1, `COMMITS=${COMMITS} (a git checkout)`);
  assert.match(COMMIT, /^[0-9a-f]{7,}$/, `COMMIT=${COMMIT}`);
  assert.equal(VERSION, `${APP_VERSION}-build.${BUILD}`);
  assert.equal(VERSION_FULL, `${VERSION} (${COMMITS} commits, ${COMMIT})`);
});

test("version.mjs --print agrees with the module and has no side effects", () => {
  const before = readFileSync(join(root, "src", "version.ts"), "utf8");
  const r = spawnSync(process.execPath, [join(root, "scripts", "version.mjs"), "--print"], {
    cwd: root,
    encoding: "utf8",
  });
  assert.equal(r.status, 0, r.stderr);
  assert.equal(r.stdout.trim(), `omakase ${VERSION_FULL}`);
  // Read-only mode must not rewrite the stamp (or bump the counter).
  assert.equal(readFileSync(join(root, "src", "version.ts"), "utf8"), before);
});

test("version.mjs --print --json reports the committed commitDate, not an empty string", () => {
  const r = spawnSync(process.execPath, [join(root, "scripts", "version.mjs"), "--print", "--json"], {
    cwd: root,
    encoding: "utf8",
  });
  assert.equal(r.status, 0, r.stderr);
  const rec = JSON.parse(r.stdout) as { build: number; commit: string; commitDate: string };
  assert.equal(rec.build, BUILD);
  assert.equal(rec.commit, COMMIT);
  // The read-only record carries the module's own provenance — a real date
  // parsed from src/version.ts, never "" (W12).
  assert.ok(rec.commitDate.length > 0, `commitDate=${rec.commitDate}`);
  assert.equal(rec.commitDate, COMMIT_DATE);
});