#!/usr/bin/env node
/**
 * omakase version stamping.
 *
 * The version is a build-time stamp: `0.1.0-build.N`, where N bumps on every
 * build (`pnpm run build:db`, `pnpm run web:build`) and on every commit (the
 * .githooks/pre-commit hook), so the version number automatically changes per
 * build and per commit. The git state (commit count, short sha, commit date)
 * is embedded as provenance so every stamp identifies exactly which commit it
 * was produced from.
 *
 * src/version.ts is the single source of truth for both the CLI and the web
 * app — they import it, so `omakase --version` and the web app's header
 * badge always agree. The build counter itself lives in the gitignored
 * `.build-number` file (never committed — commit src/version.ts instead); it
 * never goes backwards because the counter is floored at the BUILD already
 * committed in src/version.ts.
 *
 * Usage:
 *   node scripts/version.mjs            bump, write src/version.ts, print the stamp
 *   node scripts/version.mjs --json     same, but print a JSON record on stdout
 *   node scripts/version.mjs --print    print the committed stamp without writing/bumping
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const VERSION_SRC = join(root, "src", "version.ts");
const COUNTER_FILE = join(root, ".build-number");

const args = new Set(process.argv.slice(2));
const printOnly = args.has("--print");
const jsonOut = args.has("--json");

function git(a) {
  const r = spawnSync("git", a, { cwd: root, encoding: "utf8" });
  return r.status === 0 ? r.stdout.trim() : null;
}

/** BUILD currently committed in src/version.ts — the monotonic floor. */
function committedBuild() {
  try {
    const m = /export const BUILD = (\d+);/.exec(readFileSync(VERSION_SRC, "utf8"));
    return m ? Number(m[1]) : 0;
  } catch {
    return 0;
  }
}

let build;
let printedStamp = null;
/** Commit date parsed from the committed src/version.ts in --print mode (see
 * the JSON output: the module's provenance, not a live git call). */
let printedCommitDate = "";
if (printOnly) {
  // Read-only mode is a pure viewer of the COMMITTED stamp in src/version.ts.
  // The pre-commit hook re-stamps before the commit exists, so the committed
  // module's git provenance can legitimately lag HEAD by one commit;
  // recomputing git fields live (the old behavior) made `--print` disagree
  // with the very module it documents. Parse the module instead — and never
  // touch the counter or the file.
  const src = readFileSync(VERSION_SRC, "utf8");
  const field = (name) => {
    const m = new RegExp(`export const ${name} = ("([^"]*)"|'([^']*)'|(\\d+));`).exec(src);
    if (!m) throw new Error(`src/version.ts is missing ${name} — run a build once to stamp it`);
    return m[2] ?? m[3] ?? Number(m[4]);
  };
  const appVersion = String(field("APP_VERSION"));
  build = Number(field("BUILD"));
  const commitCount = Number(field("COMMITS"));
  const commit = String(field("COMMIT"));
  printedCommitDate = String(field("COMMIT_DATE"));
  printedStamp = `${appVersion}-build.${build} (${commitCount} commits, ${commit})`;
} else {
  let stored = 0;
  try {
    stored = Number(readFileSync(COUNTER_FILE, "utf8").trim() || "0") || 0;
  } catch { /* no counter yet — first stamp */ }
  // Never go backwards: a fresh clone (no counter file) starts one above the
  // last committed stamp; a build right after a commit follows the counter.
  build = Math.max(stored + 1, committedBuild() + 1);
  writeFileSync(COUNTER_FILE, `${build}\n`);
  writeFileSync(VERSION_SRC, `/**
 * omakase build version — GENERATED by scripts/version.mjs. Do not edit.
 *
 * Regenerated (and the build counter bumped) by every build — pnpm run
 * build:db / web:build — and by the pre-commit git hook, so the version
 * changes automatically on every build and every commit.
 */
export const APP_VERSION = ${JSON.stringify(pkg().version ?? "0.0.0")};
export const BUILD = ${build};
export const COMMITS = ${commits()};
export const COMMIT = ${JSON.stringify(shortSha())};
export const COMMIT_DATE = ${JSON.stringify(commitDate())};
export const VERSION = \`\${APP_VERSION}-build.\${BUILD}\`;
export const VERSION_FULL = \`\${VERSION} (\${COMMITS} commits, \${COMMIT})\`;
`);
}

function pkg() {
  return JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
}
function commits() {
  return Number(git(["rev-list", "--count", "HEAD"]) ?? 0);
}
function shortSha() {
  return git(["rev-parse", "--short", "HEAD"]) ?? "unknown";
}
function commitDate() {
  return git(["log", "-1", "--format=%cI"]) ?? "";
}

const versionFull = printedStamp ?? `${pkg().version}-build.${build} (${commits()} commits, ${shortSha()})`;
if (jsonOut) {
  process.stdout.write(JSON.stringify({
    version: pkg().version,
    build,
    commits: printedStamp ? Number(printedStamp.match(/\((\d+) commits/)?.[1] ?? 0) : commits(),
    commit: printedStamp ? printedStamp.match(/, ([0-9a-f]+)\)/)?.[1] ?? "unknown" : shortSha(),
    commitDate: printedStamp ? printedCommitDate : commitDate(),
    versionFull,
    line: `omakase ${versionFull}`,
  }) + "\n");
} else {
  process.stdout.write(`omakase ${versionFull}\n`);
}