/**
 * Output formatters — the CLI output contract, byte-identical to the golden
 * files generated by tests/fixtures/scripts/render-goldens.py.
 */
import { FORM_ORDER, type ConjClass } from "./conjugation.js";
import type {
  LoadedWord,
  LoadedKanji,
  LoadedSentence,
  SearchHit,
  KanjiReadingHit,
  KanjiWordHit,
  ThesaurusHit,
} from "./lookup.js";
import { displayHeader as lookupHeader, glossQueryTokens, isKanaInput, rubyFor } from "./lookup.js";

export interface ConjRow {
  class: string;
  form: string;
  value: string;
  display: string | null;
}

export interface WordLike {
  id: string;
  kanji: { text: string; common: boolean }[];
  kana: { text: string; common: boolean }[];
  sense: { partOfSpeech: string[] }[];
}

/** Form key -> display label (mirrors render-goldens.py FORM_LABELS). */
export const FORM_LABELS: Record<string, string> = {
  dictionary: "dictionary",
  polite_nonpast: "polite nonpast",
  polite_past: "polite past",
  polite_negative: "polite negative",
  polite_past_negative: "polite past negative",
  te_form: "te-form",
  ta_form: "ta-form (past)",
  nai_form: "nai-form (negative)",
  nakatta_form: "nakatta (neg. past)",
  potential: "potential",
  passive: "passive",
  causative: "causative",
  imperative: "imperative",
  volitional: "volitional",
  conditional_ba: "conditional -ba",
  conditional_tara: "conditional -tara",
  negative: "negative",
  past: "past",
  past_negative: "past negative",
  adverbial: "adverbial",
  attributive: "attributive",
};

/** First common kanji writing + first common kana reading (render-goldens display_header). */
export function displayHeader(word: WordLike): { text: string; reading: string | null; common: boolean } {
  const w = word.kanji.find((k) => k.common) ?? word.kanji[0];
  const r = word.kana.find((k) => k.common) ?? word.kana[0];
  const text = w ? w.text : r ? r.text : "?";
  const reading = r ? r.text : null;
  const common = word.kanji.some((k) => k.common) || word.kana.some((k) => k.common);
  return { text, reading, common };
}

/** JMdict tag -> human description, first letter capitalized (render-goldens pos_label). */
export function posLabel(tags: Record<string, string>, tag: string): string {
  const desc = tags[tag] ?? tag;
  return desc ? desc[0]!.toUpperCase() + desc.slice(1) : desc;
}

function posLine(word: WordLike, tags: Record<string, string>): string {
  const labels = [...new Set(
    word.sense.flatMap((s) => s.partOfSpeech).map((p) => posLabel(tags, p)),
  )].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
  const rest = labels.slice(1).map((l) => l.toLowerCase()).join("; ");
  return labels[0] + (labels.length > 1 ? "; " + rest : "");
}

function displayValue(row: ConjRow): string {
  return row.display ?? row.value;
}

/**
 * `conjugate <word>` output. Rows are ordered by the class form taxonomy
 * (conjugation-engine.md §3), matching the golden files' insertion order.
 */
export function renderConjugate(word: WordLike, rows: ConjRow[]): string {
  const { text, reading } = displayHeader(word);
  const lines: string[] = [`Conjugations of ${text} [${reading}]`, ""];
  const classes = [...new Set(rows.map((r) => r.class))].sort();
  const byForm = new Map(rows.map((r) => [r.form, r] as const));
  const emitted = new Set<string>();
  for (const cls of classes) {
    for (const form of FORM_ORDER[cls as ConjClass] ?? []) {
      if (emitted.has(form)) continue;
      const row = byForm.get(form);
      if (!row) continue;
      emitted.add(form);
      const label = FORM_LABELS[form] ?? form;
      lines.push(`  ${label.padEnd(22)} ${displayValue(row)}`);
    }
  }
  return lines.join("\n") + "\n";
}

/**
 * `deconjugate <form>` output. Matches are the word entries whose
 * conjugation table contains the form (display or kana value).
 */
export function renderDeconjugate(
  form: string,
  matches: { word: WordLike; formLabel: string }[],
  tags: Record<string, string>,
): string {
  const lines: string[] = [form, ""];
  for (const m of matches) {
    const { text, reading } = displayHeader(m.word);
    lines.push(`  ${text}  [${reading}]  ${posLine(m.word, tags)}  (← ${m.formLabel})`);
  }
  if (matches.length === 0) lines.push("  (no matches)");
  return lines.join("\n") + "\n";
}

/**
 * `word <query>` body: header, writings/readings/furigana, POS, numbered
 * senses. Renders the body only — the caller appends the Examples section
 * (renderExamples) when present, mirroring render-goldens.py `render_word`.
 */
export function renderWordBody(word: LoadedWord, tags: Record<string, string>, limit?: number): string {
  const h = lookupHeader(word);
  const lines: string[] = [];
  const tag = word.common ? " (common)" : "";
  lines.push(`${h.text} [${h.reading ?? ""}]${tag}`);
  lines.push("");
  if (word.kanji.length > 0) {
    lines.push("Writings: " + word.kanji.map((k) => k.text).join("・"));
  }
  lines.push("Readings: " + word.kana.map((k) => k.text).join("・"));
  if (word.kanji.length > 0) {
    // Only show a Furigana line when there is an actual ruby annotation: a
    // writing with no known split would otherwise echo the Writings line.
    const c = word.kanji.filter((k) => k.common)[0] ?? word.kanji[0]!;
    const ruby = rubyFor(word, c.text);
    if (ruby !== c.text) lines.push("Furigana: " + ruby);
  } else {
    lines.push("Furigana: " + (h.reading ?? ""));
  }
  lines.push("");

  const labels = [...new Set(word.senses.flatMap((s) => s.partOfSpeech).map((p) => posLabel(tags, p)))]
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
  lines.push(labels[0] + (labels.length > 1 ? "; " + labels.slice(1).map((l) => l.toLowerCase()).join("; ") : ""));
  lines.push("");

  const shown = limit === undefined ? word.senses : word.senses.slice(0, limit);
  shown.forEach((s, i) => {
    lines.push(`  ${i + 1}. ${s.glosses.join("; ")}`);
  });
  if (limit !== undefined && word.senses.length > limit) {
    lines.push(`  … and ${word.senses.length - limit} more senses`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Thesaurus sections (render-goldens render_thesaurus): up to 5 synonyms and
 * up to 5 antonyms as `text [reading] gloss` rows. Returns "" when empty.
 */
export function renderThesaurus(synonyms: ThesaurusHit[], antonyms: ThesaurusHit[]): string {
  const sections: string[] = [];
  if (synonyms.length > 0) {
    sections.push("Synonyms:", ...synonyms.map((s) => thesaurusRow(s)));
  }
  if (antonyms.length > 0) {
    if (sections.length > 0) sections.push("");
    sections.push("Antonyms:", ...antonyms.map((a) => thesaurusRow(a)));
  }
  return sections.length === 0 ? "" : sections.join("\n") + "\n";
}

function thesaurusRow(hit: ThesaurusHit): string {
  const { text, reading } = lookupHeader(hit.word);
  return `  ${text}  [${reading ?? ""}]  ${hit.gloss}`;
}

/** Examples section (render-goldens render_examples), or "" when none. */
export function renderExamples(examples: LoadedSentence[]): string {
  if (examples.length === 0) return "";
  const lines: string[] = ["Examples:", ""];
  examples.forEach((s, i) => {
    lines.push(`  ${i + 1}. ${s.japanese}`);
    lines.push(`     ${s.english}`);
  });
  return lines.join("\n") + "\n";
}

/**
 * `kanji <literal>` page (render-goldens render_kanji).
 * `radicalDisplay` is the precomputed `食 (184)` string (or null to omit).
 * When the compounds list was capped (kanji.compoundTotal > shown count) a
 * trailing “… and N more” note reports the rest.
 */
export function renderKanji(kanji: LoadedKanji, radicalDisplay: string | null): string {
  const lines: string[] = [];
  lines.push(`${kanji.literal}  [${kanji.strokeCount ?? "?"} strokes]`);
  lines.push("");
  const bits: string[] = [];
  if (kanji.grade) bits.push(`grade ${kanji.grade}`);
  if (kanji.jlptLevel) bits.push(`JLPT ${kanji.jlptLevel}`);
  if (kanji.frequency) bits.push(`frequency ${kanji.frequency}`);
  if (radicalDisplay) bits.push(`radical ${radicalDisplay}`);
  lines.push(bits.join(" · "));
  lines.push("");
  if (kanji.on.length > 0) lines.push("On:   " + kanji.on.join("  "));
  if (kanji.kun.length > 0) lines.push("Kun:  " + kanji.kun.join("  "));
  if (kanji.nanori.length > 0) lines.push("Nanori: " + kanji.nanori.join(" "));
  lines.push("");
  lines.push("Meanings: " + kanji.meanings.join("; "));
  lines.push("");
  if (kanji.compounds.length > 0) {
    lines.push("Compounds:");
    for (const c of kanji.compounds) {
      lines.push(`  ${c.writing}  [${c.ruby}]  ${c.gloss}`);
    }
    if (kanji.compoundTotal > kanji.compounds.length) {
      lines.push(`  … and ${kanji.compoundTotal - kanji.compounds.length} more`);
    }
  }
  return lines.join("\n") + "\n";
}

/**
 * Multi-kanji “Words” section (render-goldens render_kanji_words): words
 * containing any of the requested kanji, ranked most-matched first, capped
 * at `max` rows, with the full candidate count in the header and a trailing
 * “… and N more” note when capped. Mirrors the search section header shape.
 */
export function renderKanjiWords(hits: KanjiWordHit[], total: number, max: number): string {
  if (hits.length === 0) return "";
  const lines: string[] = [`Words (${total}):`];
  for (const h of hits) {
    lines.push(`  ${h.writing}  [${h.ruby}]  ${h.gloss}`);
  }
  if (total > hits.length) {
    lines.push(`  … and ${total - hits.length} more`);
  }
  return lines.join("\n") + "\n";
}

function kanjiHitRow(k: KanjiReadingHit): string {
  return `  ${k.literal}  [${k.readings.join("  ")}]  ${k.meanings.join("; ")}`;
}

// ---- search rendering ------------------------------------------------------

/** ANSI codes for bold (the only styling the search output uses). */
const BOLD = "\u001b[1m";
const BOLD_OFF = "\u001b[22m";

/** Default per-section cap for `search` rows; raise with `--max N`. */
export const SEARCH_MAX_DEFAULT = 30;

/** Default per-query cap for `kanji` (compounds, multi-kanji words, reading hits). */
export const KANJI_MAX_DEFAULT = 30;

/**
 * Wrap `ranges` (ascending [start, end) substrings of `text`) in bold when
 * `color` is on; otherwise return `text` unchanged (pipes and tests stay
 * plain). Ranges are clamped to the text and deduplicated.
 */
function applyBold(text: string, ranges: [number, number][], color: boolean): string {
  if (!color || ranges.length === 0) return text;
  let out = "";
  let last = 0;
  for (const [s, e] of ranges) {
    if (e <= last) continue;
    const start = Math.max(s, last);
    if (start > last) out += text.slice(last, start);
    out += BOLD + text.slice(start, e) + BOLD_OFF;
    last = e;
  }
  return out + text.slice(last);
}

/**
 * Bold the literal overlap of the query tokens inside a gloss: for each
 * gloss word, the longest query token that prefixes it (case-insensitive)
 * marks `token.length` chars at the word start (``develop`` bolds
 * ``develop`` inside ``development``; an exact match bolds the whole word).
 */
function glossBoldRanges(text: string, tokens: string[]): [number, number][] {
  const ranges: [number, number][] = [];
  const re = /[a-z0-9]+/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    const word = m[0].toLowerCase();
    let len = 0;
    for (const t of tokens) {
      if (word.startsWith(t) && t.length > len) len = t.length;
    }
    if (len > 0) ranges.push([m.index, m.index + len]);
  }
  return ranges;
}

/** One reading-section row: `text  [kana (romaji)]  gloss`, overlap bolded. */
function readingRow(hit: SearchHit, needle: string, kanaQuery: boolean, color: boolean): string {
  const { text } = lookupHeader(hit.word);
  let reading = hit.reading;
  let romaji = hit.romaji ?? "";
  if (color && needle) {
    if (kanaQuery) {
      if (reading.startsWith(needle)) reading = applyBold(reading, [[0, needle.length]], true);
    } else if (romaji.toLowerCase().startsWith(needle)) {
      romaji = applyBold(romaji, [[0, needle.length]], true);
    }
  }
  const bracket = romaji ? `${reading} (${romaji})` : reading;
  return `  ${text}  [${bracket}]  ${hit.gloss}`;
}

/** One meaning-section row: `text  [reading]  gloss`, gloss overlap bolded. */
function meaningRow(hit: SearchHit, tokens: string[], color: boolean): string {
  const { text } = lookupHeader(hit.word);
  const gloss = color ? applyBold(hit.gloss, glossBoldRanges(hit.gloss, tokens), true) : hit.gloss;
  return `  ${text}  [${hit.reading}]  ${gloss}`;
}

/**
 * `search <query>` result list. Word hits are split into two ranked
 * sections — `Readings` (reading-prefix matches, shown with their romaji)
 * and `Meanings` (gloss matches) — with kanji-by-reading matches in a
 * trailing `Kanji` section. Sections are omitted when empty; each section
 * shows at most `max` rows (default SEARCH_MAX_DEFAULT, `--max` raises it),
 * with the remainder counted in the header and a trailing note. When
 * `color` is on, literal query overlap is bolded (romaji/kana for reading
 * hits, gloss words for meaning hits) — pipes and captures stay plain.
 * Mirrors render-goldens.py `render_search`.
 */
export function renderSearch(
  query: string,
  readings: SearchHit[],
  meanings: SearchHit[],
  kanjiHits: KanjiReadingHit[] = [],
  opts: { max?: number; color?: boolean } = {},
): string {
  const max = opts.max ?? SEARCH_MAX_DEFAULT;
  const color = opts.color ?? false;
  const kanaQuery = isKanaInput(query);
  const needle = kanaQuery ? query.replace(/\s+/g, "") : query.toLowerCase().replace(/\s+/g, "");
  const tokens = glossQueryTokens(query);

  const lines: string[] = [query, ""];
  let any = false;

  const addSection = (title: string, rows: string[], total: number): void => {
    if (total === 0) return;
    if (any) lines.push("");
    any = true;
    lines.push(`${title} (${total}):`);
    const shown = rows.slice(0, max);
    lines.push(...shown);
    if (total > max) lines.push(`  … and ${total - max} more`);
  };

  if (readings.length > 0) {
    addSection("Readings", readings.map((h) => readingRow(h, needle, kanaQuery, color)), readings.length);
  }
  if (meanings.length > 0) {
    addSection("Meanings", meanings.map((h) => meaningRow(h, tokens, color)), meanings.length);
  }
  if (kanjiHits.length > 0) {
    addSection("Kanji", kanjiHits.map(kanjiHitRow), kanjiHits.length);
  }
  if (!any) lines.push("  (no results)");
  return lines.join("\n") + "\n";
}

/** `kanji <reading>` result list — same rows as the search Kanji section. */
export function renderKanjiReadingSearch(query: string, hits: KanjiReadingHit[], max?: number): string {
  const lines: string[] = [query, ""];
  const shown = max === undefined ? hits : hits.slice(0, max);
  for (const k of shown) lines.push(kanjiHitRow(k));
  if (hits.length === 0) lines.push("  (no results)");
  if (max !== undefined && hits.length > shown.length) {
    lines.push(`  … and ${hits.length - shown.length} more`);
  }
  return lines.join("\n") + "\n";
}
