/**
 * Output formatters — the CLI output contract, byte-identical to the golden
 * files generated by tests/fixtures/scripts/render-goldens.py.
 */
import { FORM_ORDER, type ConjClass } from "./conjugation.js";

export interface ConjRow {
  class: string;
  form: string;
  value: string;
  display: string | null;
}

export interface WordLike {
  id: string;
  kanji: { text: string; common: boolean }[];
  kana: { text: string; common: boolean }[];
  sense: { partOfSpeech: string[] }[];
}

/** Form key -> display label (mirrors render-goldens.py FORM_LABELS). */
export const FORM_LABELS: Record<string, string> = {
  dictionary: "dictionary",
  polite_nonpast: "polite nonpast",
  polite_past: "polite past",
  polite_negative: "polite negative",
  polite_past_negative: "polite past negative",
  te_form: "te-form",
  ta_form: "ta-form (past)",
  nai_form: "nai-form (negative)",
  nakatta_form: "nakatta (neg. past)",
  potential: "potential",
  passive: "passive",
  causative: "causative",
  imperative: "imperative",
  volitional: "volitional",
  conditional_ba: "conditional -ba",
  conditional_tara: "conditional -tara",
  negative: "negative",
  past: "past",
  past_negative: "past negative",
  adverbial: "adverbial",
  attributive: "attributive",
};

/** First common kanji writing + first common kana reading (render-goldens display_header). */
export function displayHeader(word: WordLike): { text: string; reading: string | null; common: boolean } {
  const w = word.kanji.find((k) => k.common) ?? word.kanji[0];
  const r = word.kana.find((k) => k.common) ?? word.kana[0];
  const text = w ? w.text : r ? r.text : "?";
  const reading = r ? r.text : null;
  const common = word.kanji.some((k) => k.common) || word.kana.some((k) => k.common);
  return { text, reading, common };
}

/** JMdict tag -> human description, first letter capitalized (render-goldens pos_label). */
export function posLabel(tags: Record<string, string>, tag: string): string {
  const desc = tags[tag] ?? tag;
  return desc ? desc[0]!.toUpperCase() + desc.slice(1) : desc;
}

function posLine(word: WordLike, tags: Record<string, string>): string {
  const labels = [...new Set(
    word.sense.flatMap((s) => s.partOfSpeech).map((p) => posLabel(tags, p)),
  )].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
  const rest = labels.slice(1).map((l) => l.toLowerCase()).join("; ");
  return labels[0] + (labels.length > 1 ? "; " + rest : "");
}

function displayValue(row: ConjRow): string {
  return row.display ?? row.value;
}

/**
 * `conjugate <word>` output. Rows are ordered by the class form taxonomy
 * (conjugation-engine.md §3), matching the golden files' insertion order.
 */
export function renderConjugate(word: WordLike, rows: ConjRow[]): string {
  const { text, reading } = displayHeader(word);
  const lines: string[] = [`Conjugations of ${text} [${reading}]`, ""];
  const classes = [...new Set(rows.map((r) => r.class))].sort();
  const byForm = new Map(rows.map((r) => [r.form, r] as const));
  const emitted = new Set<string>();
  for (const cls of classes) {
    for (const form of FORM_ORDER[cls as ConjClass] ?? []) {
      if (emitted.has(form)) continue;
      const row = byForm.get(form);
      if (!row) continue;
      emitted.add(form);
      const label = FORM_LABELS[form] ?? form;
      lines.push(`  ${label.padEnd(22)} ${displayValue(row)}`);
    }
  }
  return lines.join("\n") + "\n";
}

/**
 * `deconjugate <form>` output. Matches are the word entries whose
 * conjugation table contains the form (display or kana value).
 */
export function renderDeconjugate(
  form: string,
  matches: { word: WordLike; formLabel: string }[],
  tags: Record<string, string>,
): string {
  const lines: string[] = [form, ""];
  for (const m of matches) {
    const { text, reading } = displayHeader(m.word);
    lines.push(`  ${text}  [${reading}]  ${posLine(m.word, tags)}  (← ${m.formLabel})`);
  }
  if (matches.length === 0) lines.push("  (no matches)");
  return lines.join("\n") + "\n";
}
