/**
 * Output formatters — the CLI output contract, byte-identical to the golden
 * files generated by tests/fixtures/scripts/render-goldens.py.
 */
import { FORM_ORDER, type ConjClass } from "./conjugation.js";
import type {
  LoadedWord,
  LoadedKanji,
  LoadedSentence,
  SearchHit,
  KanjiReadingHit,
} from "./lookup.js";
import { displayHeader as lookupHeader, rubyFor } from "./lookup.js";

export interface ConjRow {
  class: string;
  form: string;
  value: string;
  display: string | null;
}

export interface WordLike {
  id: string;
  kanji: { text: string; common: boolean }[];
  kana: { text: string; common: boolean }[];
  sense: { partOfSpeech: string[] }[];
}

/** Form key -> display label (mirrors render-goldens.py FORM_LABELS). */
export const FORM_LABELS: Record<string, string> = {
  dictionary: "dictionary",
  polite_nonpast: "polite nonpast",
  polite_past: "polite past",
  polite_negative: "polite negative",
  polite_past_negative: "polite past negative",
  te_form: "te-form",
  ta_form: "ta-form (past)",
  nai_form: "nai-form (negative)",
  nakatta_form: "nakatta (neg. past)",
  potential: "potential",
  passive: "passive",
  causative: "causative",
  imperative: "imperative",
  volitional: "volitional",
  conditional_ba: "conditional -ba",
  conditional_tara: "conditional -tara",
  negative: "negative",
  past: "past",
  past_negative: "past negative",
  adverbial: "adverbial",
  attributive: "attributive",
};

/** First common kanji writing + first common kana reading (render-goldens display_header). */
export function displayHeader(word: WordLike): { text: string; reading: string | null; common: boolean } {
  const w = word.kanji.find((k) => k.common) ?? word.kanji[0];
  const r = word.kana.find((k) => k.common) ?? word.kana[0];
  const text = w ? w.text : r ? r.text : "?";
  const reading = r ? r.text : null;
  const common = word.kanji.some((k) => k.common) || word.kana.some((k) => k.common);
  return { text, reading, common };
}

/** JMdict tag -> human description, first letter capitalized (render-goldens pos_label). */
export function posLabel(tags: Record<string, string>, tag: string): string {
  const desc = tags[tag] ?? tag;
  return desc ? desc[0]!.toUpperCase() + desc.slice(1) : desc;
}

function posLine(word: WordLike, tags: Record<string, string>): string {
  const labels = [...new Set(
    word.sense.flatMap((s) => s.partOfSpeech).map((p) => posLabel(tags, p)),
  )].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
  const rest = labels.slice(1).map((l) => l.toLowerCase()).join("; ");
  return labels[0] + (labels.length > 1 ? "; " + rest : "");
}

function displayValue(row: ConjRow): string {
  return row.display ?? row.value;
}

/**
 * `conjugate <word>` output. Rows are ordered by the class form taxonomy
 * (conjugation-engine.md §3), matching the golden files' insertion order.
 */
export function renderConjugate(word: WordLike, rows: ConjRow[]): string {
  const { text, reading } = displayHeader(word);
  const lines: string[] = [`Conjugations of ${text} [${reading}]`, ""];
  const classes = [...new Set(rows.map((r) => r.class))].sort();
  const byForm = new Map(rows.map((r) => [r.form, r] as const));
  const emitted = new Set<string>();
  for (const cls of classes) {
    for (const form of FORM_ORDER[cls as ConjClass] ?? []) {
      if (emitted.has(form)) continue;
      const row = byForm.get(form);
      if (!row) continue;
      emitted.add(form);
      const label = FORM_LABELS[form] ?? form;
      lines.push(`  ${label.padEnd(22)} ${displayValue(row)}`);
    }
  }
  return lines.join("\n") + "\n";
}

/**
 * `deconjugate <form>` output. Matches are the word entries whose
 * conjugation table contains the form (display or kana value).
 */
export function renderDeconjugate(
  form: string,
  matches: { word: WordLike; formLabel: string }[],
  tags: Record<string, string>,
): string {
  const lines: string[] = [form, ""];
  for (const m of matches) {
    const { text, reading } = displayHeader(m.word);
    lines.push(`  ${text}  [${reading}]  ${posLine(m.word, tags)}  (← ${m.formLabel})`);
  }
  if (matches.length === 0) lines.push("  (no matches)");
  return lines.join("\n") + "\n";
}

/**
 * `word <query>` body: header, writings/readings/furigana, POS, numbered
 * senses. Renders the body only — the caller appends the Examples section
 * (renderExamples) when present, mirroring render-goldens.py `render_word`.
 */
export function renderWordBody(word: LoadedWord, tags: Record<string, string>, limit?: number): string {
  const h = lookupHeader(word);
  const lines: string[] = [];
  const tag = word.common ? " (common)" : "";
  lines.push(`${h.text} [${h.reading ?? ""}]${tag}`);
  lines.push("");
  if (word.kanji.length > 0) {
    lines.push("Writings: " + word.kanji.map((k) => k.text).join("・"));
  }
  lines.push("Readings: " + word.kana.map((k) => k.text).join("・"));
  if (word.kanji.length > 0) {
    const c = word.kanji.filter((k) => k.common)[0] ?? word.kanji[0]!;
    lines.push("Furigana: " + rubyFor(word, c.text));
  } else {
    lines.push("Furigana: " + (h.reading ?? ""));
  }
  lines.push("");

  const labels = [...new Set(word.senses.flatMap((s) => s.partOfSpeech).map((p) => posLabel(tags, p)))]
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
  lines.push(labels[0] + (labels.length > 1 ? "; " + labels.slice(1).map((l) => l.toLowerCase()).join("; ") : ""));
  lines.push("");

  const shown = limit === undefined ? word.senses : word.senses.slice(0, limit);
  shown.forEach((s, i) => {
    lines.push(`  ${i + 1}. ${s.glosses.join("; ")}`);
  });
  if (limit !== undefined && word.senses.length > limit) {
    lines.push(`  … and ${word.senses.length - limit} more senses`);
  }
  return lines.join("\n") + "\n";
}

/** Examples section (render-goldens render_examples), or "" when none. */
export function renderExamples(examples: LoadedSentence[]): string {
  if (examples.length === 0) return "";
  const lines: string[] = ["Examples:", ""];
  examples.forEach((s, i) => {
    lines.push(`  ${i + 1}. ${s.japanese}`);
    lines.push(`     ${s.english}`);
  });
  return lines.join("\n") + "\n";
}

/**
 * `kanji <literal>` page (render-goldens render_kanji).
 * `radicalDisplay` is the precomputed `食 (184)` string (or null to omit).
 */
export function renderKanji(kanji: LoadedKanji, radicalDisplay: string | null): string {
  const lines: string[] = [];
  lines.push(`${kanji.literal}  [${kanji.strokeCount ?? "?"} strokes]`);
  lines.push("");
  const bits: string[] = [];
  if (kanji.grade) bits.push(`grade ${kanji.grade}`);
  if (kanji.jlptLevel) bits.push(`JLPT ${kanji.jlptLevel}`);
  if (kanji.frequency) bits.push(`frequency ${kanji.frequency}`);
  if (radicalDisplay) bits.push(`radical ${radicalDisplay}`);
  lines.push(bits.join(" · "));
  lines.push("");
  if (kanji.on.length > 0) lines.push("On:   " + kanji.on.join("  "));
  if (kanji.kun.length > 0) lines.push("Kun:  " + kanji.kun.join("  "));
  if (kanji.nanori.length > 0) lines.push("Nanori: " + kanji.nanori.join(" "));
  lines.push("");
  lines.push("Meanings: " + kanji.meanings.join("; "));
  lines.push("");
  if (kanji.compounds.length > 0) {
    lines.push("Compounds:");
    for (const c of kanji.compounds) {
      lines.push(`  ${c.writing}  [${c.ruby}]  ${c.gloss}`);
    }
  }
  return lines.join("\n") + "\n";
}

function kanjiHitRow(k: KanjiReadingHit): string {
  return `  ${k.literal}  [${k.readings.join("  ")}]  ${k.meanings.join("; ")}`;
}

/**
 * `search <query>` result list (render-goldens render_search). When `kanjiHits`
 * is non-empty, a "Kanji:" section is appended, mirroring how Tangorin shows
 * word and kanji results side by side.
 */
export function renderSearch(query: string, hits: SearchHit[], kanjiHits: KanjiReadingHit[] = []): string {
  const lines: string[] = [query, ""];
  for (const hit of hits) {
    const { text } = lookupHeader(hit.word);
    lines.push(`  ${text}  [${hit.reading}]  ${hit.gloss}`);
  }
  if (kanjiHits.length > 0) {
    lines.push("", "Kanji:");
    for (const k of kanjiHits) lines.push(kanjiHitRow(k));
  }
  if (hits.length === 0 && kanjiHits.length === 0) lines.push("  (no results)");
  return lines.join("\n") + "\n";
}

/** `kanji <reading>` result list — same rows as the search Kanji section. */
export function renderKanjiReadingSearch(query: string, hits: KanjiReadingHit[]): string {
  const lines: string[] = [query, ""];
  for (const k of hits) lines.push(kanjiHitRow(k));
  if (hits.length === 0) lines.push("  (no results)");
  return lines.join("\n") + "\n";
}
