/**
 * omakase build version — GENERATED by scripts/version.mjs. Do not edit.
 *
 * Regenerated (and the build counter bumped) by every build — pnpm run
 * build:db / web:build — and by the pre-commit git hook, so the version
 * changes automatically on every build and every commit.
 */
export const APP_VERSION = "0.1.0";
export const BUILD = 211;
export const COMMITS = 66;
export const COMMIT = "e8e8e89";
export const COMMIT_DATE = "2026-09-12T11:42:54+02:00";
export const VERSION = `${APP_VERSION}-build.${BUILD}`;
export const VERSION_FULL = `${VERSION} (${COMMITS} commits, ${COMMIT})`;
